### ISSUE TITLE
SeuratToExpressionSet

### ISSUE THREAD

**Issue by chenx9** [cozygene/bisque#31]
hi,when I run the code 'sc.eset <- BisqueRNA::SeuratToExpressionSet(seurat, delimiter="-", position=2, version="v3")',I get the errow below
   sc.eset <- BisqueRNA::SeuratToExpressionSet(seurat, delimiter="-", position=2, version="v3")
Split sample names by "-" and checked position 2. Found 18 individuals.
Example: "AAACCCAAGAAGCTCG-1" corresponds to individual "1".
Error in asMethod(object) : 
  Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 102

**Comment by brandonjew** [comment]
Hi @chenx9,

Thanks for your interest in our method! I believe that error arises when the expression data in the seurat object is too large. The object is fine before the conversion since it's stored as a sparse matrix, but it is converted to a dense matrix by this function. As far as I can tell, the ExpressionSet object does not support sparse matrices. Unfortunately, this would require editing the Biobase:::ExpressionSet source code or finding a machine with more memory. Please let me know if you have any other questions.

Thanks,
Brandon

**Comment by chenx9** [comment]
Thanks for your reply.
I tried the Biobase:::ExpressionSet function and got a similar error.
Does that mean I can't use it to process large data sets? 

Thanks

**Comment by brandonjew** [comment]
That's correct, someone would have to edit the ExpressionSet source code to use sparse matrices. Tools like CIBERSORTx have a web server that will handle the computation on their side if you're comfortable uploading the data.
