### ISSUE TITLE
Deconvolution for a specific part of bulk tissue RNAseq using scRNAseq data?

### ISSUE THREAD

**Issue by hellocita** [cozygene/bisque#6]
Hello!
I want to use BisqueRNA for deconvolution of a specific part of bulk tissue. 
The bulk tissue has 4 part biologically: part A, B, C, D, while their cell type composition is totally different. And only part A were measure in bulk RNA-seq. However, the whole tissue (with part A, B, C, D all included) is used in sc RNA-seq. And I am trying to predict the cell type composition in part A afterwards.
I wonder if I am doing right, and if the composition of a part of tissue will affect the deconvolution performance in BisqueRNA. 
thanks in advance for your help!

**Comment by brandonjew** [comment]
Hi,

The differing composition of the reference scRNA-seq and bulk RNA-seq samples will affect BisqueRNA reference-based performance since the method assumes that the samples represent the same tissues. Unless the scRNA-seq data can be separated into the cells that came from each tissue parts, the marker-based decomposition in the BisqueRNA package may be better to use in this case. Please let me know if you have any other questions and thank you for your interest!

Brandon
